//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbuixechHealthcareCentre.pages
{
    public partial class Doctor
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm doctorForm;

        protected global::System.Web.UI.WebControls.TextBox SearchTextBox;

        protected global::System.Web.UI.WebControls.Button SearchButton;

        protected global::System.Web.UI.WebControls.GridView PatientGridView;

        protected global::System.Web.UI.WebControls.Label NoPatientSelectedLabel;

        protected global::System.Web.UI.WebControls.GridView MedicalRecordGridView;

        protected global::System.Web.UI.WebControls.Button CreateRecordButton;

        protected global::System.Web.UI.WebControls.Panel MedicalRecordForm;

        protected global::System.Web.UI.WebControls.HiddenField RecordIDHiddenField;

        protected global::System.Web.UI.WebControls.TextBox AppointmentDateTextBox;

        protected global::System.Web.UI.WebControls.TextBox DiagnosisTextBox;

        protected global::System.Web.UI.WebControls.TextBox TreatmentTextBox;

        protected global::System.Web.UI.WebControls.Button SaveRecordButton;

        protected global::System.Web.UI.WebControls.Button CancelEditButton;
    }
}

