//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbuixechHealthcareCentre.pages
{
    public partial class PatientPage
    {
        /// <summary>
        /// Control PatientNameLabel.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo de diseño al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label PatientNameLabel;

        /// <summary>
        /// Control DateOfBirthLabel.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo de diseño al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label DateOfBirthLabel;

        /// <summary>
        /// Control AddressLabel.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo de diseño al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label AddressLabel;

        /// <summary>
        /// Control MobileLabel.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo de diseño al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label MobileLabel;

        /// <summary>
        /// Control PINLabel.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo de diseño al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label PINLabel;

        /// <summary>
        /// Control MedicalRecordGridView.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo de diseño al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView MedicalRecordGridView;
    }
}
