//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbuixechHealthcareCentre.pages
{
    public partial class UpdatePatient
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm UpdatePatientForm;

        protected global::System.Web.UI.WebControls.TextBox NameTextBox;

        protected global::System.Web.UI.WebControls.TextBox DateOfBirthTextBox;

        protected global::System.Web.UI.WebControls.TextBox AddressTextBox;

        protected global::System.Web.UI.WebControls.TextBox MobileTextBox;

        protected global::System.Web.UI.WebControls.TextBox PINTextBox;

        protected global::System.Web.UI.WebControls.TextBox UsernameTextBox;

        protected global::System.Web.UI.WebControls.TextBox PasswordTextBox;

        protected global::System.Web.UI.WebControls.DropDownList RoleDropDown;

        protected global::System.Web.UI.WebControls.Button UpdatePatientButton;
    }
}
